#!/bin/bash

echo "🚀 KICKAI GitHub Project Setup Helper"
echo "====================================="
echo ""

echo "📋 Step-by-step instructions to import github_project_import.md to GitHub:"
echo ""

echo "1️⃣  CREATE GITHUB PROJECT:"
echo "   - Go to your KICKAI repository on GitHub"
echo "   - Click 'Projects' tab"
echo "   - Click 'New project'"
echo "   - Choose 'Board' type"
echo "   - Name it 'KICKAI Development'"
echo "   - Click 'Create'"
echo ""

echo "2️⃣  SET UP COLUMNS:"
echo "   Create these columns in your project:"
echo "   - Backlog"
echo "   - To Do"
echo "   - In Progress"
echo "   - Review"
echo "   - Done"
echo ""

echo "3️⃣  CREATE LABELS:"
echo "   Go to Issues → Labels and create these labels:"
echo ""

# High Priority Labels
echo "🔴 HIGH PRIORITY:"
echo "   - high-priority (red)"
echo "   - infrastructure (blue)"
echo "   - database (blue)"
echo "   - api (blue)"
echo "   - whatsapp (blue)"
echo "   - agents (blue)"
echo "   - tools (blue)"
echo "   - communication (blue)"
echo "   - management (blue)"
echo "   - fixtures (blue)"
echo "   - availability (blue)"
echo "   - squad (blue)"
echo "   - finance (blue)"
echo "   - testing (blue)"
echo "   - documentation (blue)"
echo ""

# Medium Priority Labels
echo "🟡 MEDIUM PRIORITY:"
echo "   - medium-priority (yellow)"
echo "   - payments (blue)"
echo "   - stripe (blue)"
echo "   - statistics (blue)"
echo "   - ratings (blue)"
echo "   - leaderboard (blue)"
echo "   - automation (blue)"
echo "   - ai (blue)"
echo "   - deployment (blue)"
echo "   - ux (blue)"
echo "   - error-handling (blue)"
echo ""

# Low Priority Labels
echo "🟢 LOW PRIORITY:"
echo "   - low-priority (green)"
echo "   - fines (blue)"
echo "   - tasks (blue)"
echo "   - reminders (blue)"
echo "   - security (blue)"
echo "   - quality (blue)"
echo ""

echo "4️⃣  IMPORT TASKS:"
echo "   There are several ways to import the tasks:"
echo ""

echo "   OPTION A: Manual Creation (Recommended for small teams)"
echo "   - Open github_project_import.md"
echo "   - Create issues manually using the format in the file"
echo "   - Add appropriate labels and assignees"
echo "   - Move to appropriate columns"
echo ""

echo "   OPTION B: GitHub CLI (Advanced)"
echo "   - Install GitHub CLI: brew install gh"
echo "   - Authenticate: gh auth login"
echo "   - Use the script below to create issues"
echo ""

echo "   OPTION C: GitHub API (For bulk import)"
echo "   - Use the Python script below for bulk creation"
echo ""

echo "5️⃣  ORGANIZE TASKS:"
echo "   - Move high-priority tasks to 'To Do'"
echo "   - Move medium-priority tasks to 'Backlog'"
echo "   - Assign team members to tasks"
echo "   - Set up milestones for Phase 1, 2, and 3"
echo ""

echo "📝 NOTES:"
echo "   - Each task in github_project_import.md has a specific format"
echo "   - Copy the title, description, and checklist for each task"
echo "   - Add the appropriate labels based on the task type"
echo "   - Consider creating milestones for each phase"
echo ""

echo "🎯 RECOMMENDED STARTING POINTS:"
echo "   1. Set up Supabase database schema"
echo "   2. Install and configure Twilio SDK"
echo "   3. Create FastAPI application structure"
echo "   4. Create Communications Officer Agent"
echo "   5. Create Manager Agent"
echo ""

echo "✅ You're ready to start importing your KICKAI project tasks!" 